<!DOCTYPE html><html lang=""><head><meta charset=utf-8><meta http-equiv=X-UA-Compatible content="IE=edge,chrome=1"><meta name=renderer content=webkit><meta name=viewport content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"><meta name=description content=中国历史最悠久的IP地理位置库,纯真IP库,免费IP库,开源IP库,全球IP地址库,IP地址,IP定位><meta name=keywords content="纯真,纯真IP库,cz88,IP查询,查IP,IP定位,IP精确定位,IP精准定位,高精度IP定位,高精度IP地址查询,
    IP地理位置,IP地址查询,IP地址定位,IPv4库,IPv6库,全球IP库,全球IP地址数据库,全球IP地理位置数据库,IP实验室,IP实验室APP"><link rel=icon href=favicon.ico><title>纯真-中国IP地理位置数据库首创者</title><link rel=stylesheet href=https://unpkg.com/swiper@8/swiper-bundle.min.css><script src=https://unpkg.com/swiper@8/swiper-bundle.min.js></script><script>var _hmt = _hmt || [];
        (function () {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?7ed3e4105fd34f70f2b3d1bb2ca8c5dc";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();</script><script async src="https://www.googletagmanager.com/gtag/js?id=G-SGEY66BFK5"></script><script>window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-SGEY66BFK5');</script><link href=assets/css/chunk-2e0308fa.28ea21d5.css rel=prefetch><link href=assets/css/chunk-3160bd7e.c3bb9bc9.css rel=prefetch><link href=assets/css/chunk-321188d6.aaffffe1.css rel=prefetch><link href=assets/css/chunk-36413cbe.fb5a202c.css rel=prefetch><link href=assets/css/chunk-3ca4d730.2f11df85.css rel=prefetch><link href=assets/css/chunk-4f95ccc7.75e3b228.css rel=prefetch><link href=assets/css/chunk-54c31f0c.cf6f62f6.css rel=prefetch><link href=assets/css/chunk-55d48c6e.77f8639a.css rel=prefetch><link href=assets/css/chunk-582289ae.13aca01f.css rel=prefetch><link href=assets/css/chunk-591162aa.ef1ed939.css rel=prefetch><link href=assets/css/chunk-5a8f31e3.72356b41.css rel=prefetch><link href=assets/css/chunk-73e76e34.48f55c14.css rel=prefetch><link href=assets/css/chunk-9280c278.c70c99d7.css rel=prefetch><link href=assets/css/chunk-96e876f2.827ca820.css rel=prefetch><link href=assets/css/chunk-9aa3f9d6.7132a7e7.css rel=prefetch><link href=assets/css/chunk-d97f7184.ae4b0492.css rel=prefetch><link href=assets/css/chunk-e151b6fc.64a04a31.css rel=prefetch><link href=assets/css/chunk-f4409a0c.a31cdba9.css rel=prefetch><link href=assets/css/chunk-f726faec.f43558cc.css rel=prefetch><link href=assets/js/chunk-2e0308fa.eda28500.js rel=prefetch><link href=assets/js/chunk-3160bd7e.0aab832b.js rel=prefetch><link href=assets/js/chunk-321188d6.38d49a08.js rel=prefetch><link href=assets/js/chunk-36413cbe.224ac2ec.js rel=prefetch><link href=assets/js/chunk-3ca4d730.d15f173b.js rel=prefetch><link href=assets/js/chunk-4f95ccc7.e05a75f0.js rel=prefetch><link href=assets/js/chunk-54c31f0c.f1ad2ced.js rel=prefetch><link href=assets/js/chunk-55d48c6e.df3e4487.js rel=prefetch><link href=assets/js/chunk-582289ae.540f92cf.js rel=prefetch><link href=assets/js/chunk-591162aa.8b31f1b9.js rel=prefetch><link href=assets/js/chunk-5a8f31e3.da3aab60.js rel=prefetch><link href=assets/js/chunk-73e76e34.3059c388.js rel=prefetch><link href=assets/js/chunk-9280c278.22b4797e.js rel=prefetch><link href=assets/js/chunk-96e876f2.1d29ea67.js rel=prefetch><link href=assets/js/chunk-9aa3f9d6.6ac4d7f4.js rel=prefetch><link href=assets/js/chunk-d97f7184.54b2e1f6.js rel=prefetch><link href=assets/js/chunk-e151b6fc.f7ebcf47.js rel=prefetch><link href=assets/js/chunk-f4409a0c.0afea851.js rel=prefetch><link href=assets/js/chunk-f726faec.a6055ea7.js rel=prefetch><link href=assets/css/app.619accd6.css rel=preload as=style><link href=assets/css/chunk-vendors.24daa450.css rel=preload as=style><link href=assets/js/app.cd0e087f.js rel=preload as=script><link href=assets/js/chunk-vendors.c4d04e14.js rel=preload as=script><link href=assets/css/chunk-vendors.24daa450.css rel=stylesheet><link href=assets/css/app.619accd6.css rel=stylesheet></head><body><noscript><strong>We're sorry but cz88 doesn't work properly without JavaScript enabled. Please enable it to continue.</strong></noscript><div id=app></div><script>// function refreshRem() {
    //   // var docEl = document.documentElement;
    //   // var width = docEl.getBoundingClientRect().width;
    //   // var rem = width / 10;

    //       var baseFontSize = 100
    //       var designWidth = 750
    //       var width = window.innerWidth
    //       var currentFontSize = (width / designWidth) * baseFontSize

    //   docEl.style.fontSize = currentFontSize + "px";
    // }
    // window.addEventListener("resize", ()=>refreshRem, false);

    // refreshRem()</script><script src=assets/js/chunk-vendors.c4d04e14.js></script><script src=assets/js/app.cd0e087f.js></script><script>(function(){var js = "window['__CF$cv$params']={r:'731dead858597c21',m:'yG8sk8QKL3meyQcTrytjk_dKZ0fD.Pw8Oy0FoVNay2k-1659014482-0-AYkm7m4Yqr8LGBmG8EHAiT57UUYOV5+yOJ+nOo+hiYX20JOQowaa/pkgxxq/LqKRiRPRV29nlEYu4R/rLP0y1kbKB9AmaNPxIbbtbc5oMzO8BbYXVo6gO0luo77iMoxUKx7gzyeBTmqIdxs++LSp2PA=',s:[0x0e15c2b6e8,0x05ca187060],u:'/cdn-cgi/challenge-platform/h/b'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body></html>